{% set upstreamversion = "5-26-2015" %}
{% set version = "20150526" %}

package:
  name: labjack
  version: {{ version }}

source:
  url: https://github.com/labjack/LabJackPython/archive/{{ upstreamversion }}.tar.gz
  sha256: 555d209018787fc55b3e83c3c11ed16ace6564e758295d8a668b5b74f34cae9e

build:
  number: 1000
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python <3
    - pip
  run:
    - python <3
test:
  imports:
    - u3
    - u6
    - ue9

about:
  home: http://labjack.com/support/labjackpython
  summary: "Python module for communicating with the LabJack U3/U6/UE9/U12"
  license: MIT X-11
  license_family: MIT

extra:
  recipe-maintainers:
    - kastman
